#!/bin/sh


if [ "$DEVICE" = "br-lan" ]; then
  if [ "$ACTION" = "ifup" ]; then
    logger -t "traffic-cop" "starting up LAN htb queue"

    # We need a default htb classful queue.
    # Since we assign handles to the last digits of people's ip address and that
    # *100 + 66, 265 is where we put all non-classified traffic as it will never
    # collide with any of that
    tc qdisc add dev br-lan root handle 1: htb default 265
    tc qdisc add dev br-lan handle ffff: ingress
    ifconfig ifb0 up
    tc qdisc add dev ifb0 root handle 1: htb default 265
  elif [ "$ACTION" = "ifdown" ]; then
    logger -t "traffic-cop" "br-lan down, all tc rules removed"
    tc qdisc del dev br-lan root
    tc qdisc del dev br-lan ingress
    tc qdisc del dev ifb0 root
    ifconfig ifb0 down
  fi
fi

